// react/mobikart/src/components/header/index.jsx
import React, { Component } from "react";
import {Link} from "react-router-dom";
import './style.scss';
import './responsive.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faSearch, faShoppingCart, faEdit, faBoxOpen,
    faHeart, faPowerOff, faBell, faPhoneAlt, faCog
} from '@fortawesome/free-solid-svg-icons';


class Header extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <header>
                <div className="logoContainer">
                    <Link to="/">
                    <img src="/assets/sitelogo.svg" alt="Company Logo" />
                    </Link>
                </div>
                <div className="searchBox">
                    <input type="text" placeholder="Search Products" />
                    <button><FontAwesomeIcon icon={faSearch} /></button>
                </div>
                <div className="menu">
                    <div className="option">
                        <a href="javascript:void(0)">Profile</a>
                        <ul className="dropdown">
                            <li><i><FontAwesomeIcon icon={faEdit} /></i> Edit Profile</li>
                            <li><i><FontAwesomeIcon icon={faBoxOpen} /></i> Orders</li>
                            <li><i><FontAwesomeIcon icon={faHeart} /></i> Whislist</li>
                            <li><i><FontAwesomeIcon icon={faPowerOff} /></i> Logout</li>
                        </ul>
                    </div>
                    <div className="option">
                        <a href="javascript:void(0)">More</a>
                        <ul className="dropdown">
                            <li><i><FontAwesomeIcon icon={faBell} /></i> Notification</li>
                            <li><i><FontAwesomeIcon icon={faPhoneAlt} /></i> 24x7 Customer Care</li>
                            <li><i><FontAwesomeIcon icon={faCog} /></i> Settings</li>
                        </ul>
                    </div>
                    <div className="option">
                        <a href="javascript:void(0)"><i><FontAwesomeIcon icon={faShoppingCart} /></i> Cart</a>
                    </div>
                </div>
            </header>
        )
    }
}

export default Header;

// angular/mobikart/src/app/components/header/header.component.ts
import { Component , OnInit } from '@angular/core';
import { faSearch, faShoppingCart, faEdit, faBoxOpen,
  faHeart, faPowerOff, faBell, faPhoneAlt, faCog } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  faSearch = faSearch;
  faEdit = faEdit;
  faBoxOpen = faBoxOpen;
  faHeart = faHeart;
  faPowerOff = faPowerOff;
  faBell = faBell;
  faPhoneAlt = faPhoneAlt;
  faCog = faCog;
  faShoppingCart = faShoppingCart;
  constructor() { }

  ngOnInit(): void {
  }

}

<header>
    <div class="logoContainer">
        <!-- <Link to="/"> -->
        <img src="/assets/sitelogo.svg" alt="Company Logo" />
        <!-- </Link> -->
    </div>
    <div class="searchBox">
        <input type="text" placeholder="Search Products" />
        <button>
            <fa-icon [icon]="faSearch"></fa-icon>
        </button>
    </div>
    <div class="menu">
        <div class="option">
            <a href="javascript:void(0)">Profile</a>
            <ul class="dropdown">
                <li><i>
                        <fa-icon [icon]="faEdit"></fa-icon>
                    </i> Edit Profile</li>
                <li><i>
                        <fa-icon [icon]="faBoxOpen"></fa-icon>
                    </i> Orders</li>
                <li><i>
                        <fa-icon [icon]="faHeart"></fa-icon>
                    </i> Whislist</li>
                <li><i>
                        <fa-icon [icon]="faPowerOff"></fa-icon>
                    </i> Logout</li>
            </ul>
        </div>
        <div class="option">
            <a href="javascript:void(0)">More</a>
            <ul class="dropdown">
                <li><i>
                        <fa-icon [icon]="faBell"></fa-icon>
                    </i> Notification</li>
                <li><i>
                        <fa-icon [icon]="faPhoneAlt"></fa-icon>
                    </i> 24x7 Customer Care</li>
                <li><i>
                        <fa-icon [icon]="faCog"></fa-icon>
                    </i> Settings</li>
            </ul>
        </div>
        <div class="option">
            <a href="javascript:void(0)"><i>
                    <fa-icon [icon]="faShoppingCart"></fa-icon>
                </i> Cart</a>
        </div>
    </div>
</header>
